In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("quikr_car.csv")

In [3]:
df.head(30  )

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
7,Hyundai Eon,Hyundai,2013,"1,90,000","25,000 kms",Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,"8,30,000","24,530 kms",Diesel
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,"2,50,000","60,000 kms",Petrol
10,Skoda Fabia Classic 1.2 MPI,Skoda,2010,"1,82,000","60,000 kms",Petrol
11,Maruti Suzuki Stingray VXi,Maruti,2015,"3,15,000","30,000 kms",Petrol
12,Hyundai Elite i20 Magna 1.2,Hyundai,2014,"4,15,000","32,000 kms",Petrol
13,Mahindra Scorpio SLE BS IV,Mahindra,2015,"3,20,000","48,660 kms",Diesel
14,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
15,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
16,Audi A8,Audi,2017,"10,00,000","4,000 kms",Petrol
17,Audi Q7,Audi,2014,"5,00,000","16,934 kms",Diesel
18,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
19,Maruti Suzuki Alto 800,Maruti,2014,"1,60,000","35,550 kms",Petrol
20,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
21,Mahindra Scorpio S10,Mahindra,2016,"3,10,000","39,522 kms",Diesel
22,Maruti Suzuki Alto 800 Vxi,Maruti,2015,"75,000","39,000 kms",Petrol
23,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
24,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
25,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
26,Maruti Suzuki Alto 800 Lx,Maruti,2017,"1,90,000","72,000 kms",Petrol
27,Maruti Suzuki Vitara Brezza ZDi,Maruti,2016,"2,90,000","15,975 kms",Diesel
28,Maruti Suzuki Alto LX,Maruti,2008,"95,000","70,000 kms",Petrol
29,Mahindra Bolero DI,Mahindra,2017,"1,80,000","23,452 kms",Diesel

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

## Quality

In [5]:
df["kms_driven"].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

> Year has many non year values
> Year is in object type
> price has some diff values, and its in diff type
> kmsdriven has kms with integer and its in diff type, and nan values
> fuel_type has nan values
> Keep first three words of name

## Cleaning

In [6]:
backup = df.copy()

In [7]:
df = df[df["year"].str.isnumeric()]

In [8]:
df["year"] = df["year"].astype(int)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB

In [10]:
df = df[df["Price"]!= "Ask For Price"]

In [11]:
df["Price"] = df["Price"].str.replace(",","").astype(int)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [13]:
df["kms_driven"] = df["kms_driven"].str.split(" ").str.get(0).str.replace(",","")

In [14]:
df=df[df["kms_driven"].str.isnumeric()]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.7+ KB

In [16]:
df["kms_driven"] = df["kms_driven"].astype(int)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

In [18]:
df = df[~df["fuel_type"].isna()]  # ~  = means excluding this row

In [19]:
df["name"] = df["name"].str.split(" ").str.slice(0,3).str.join(" ")
# split use for spliting every word by space, with the slice we getting first three words after we join it

In [20]:
df = df.reset_index(drop = True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [22]:
df.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [23]:
df = df[df["Price"] < 6e6].reset_index(drop = True)  #60lakh means 6e6

In [24]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [25]:
df.to_csv("Cleaned car.csv")

## Model

In [26]:
X = df.drop(columns = "Price")
y = df["Price"]

In [27]:
X.shape

(815, 5)

In [28]:
y.shape  #Target Column

(815,)

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [30]:
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [31]:
ohe = OneHotEncoder()
ohe.fit(X[["name","company","fuel_type"]])

OneHotEncoder()

In [32]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_),["name","company","fuel_type"]),
                                       remainder = "passthrough")

In [33]:
lr = LinearRegression()

In [34]:
pipe = make_pipeline(column_trans,lr)

In [35]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [36]:
y_pred = pipe.predict(X_test)

In [37]:
y_pred

array([ 285271.71202426,  205638.8912681 ,  300344.42795834,
       2145935.36861171,  403042.35332692,  490575.90127359,
       1521854.24893257,   83945.4552588 ,  420180.68652553,
        442614.00832499,  698751.06408977,  587439.463265  ,
        477671.76607265,  322668.11754873,  433837.48789667,
        644314.57593225, 1613254.61024456,  280531.55117001,
        338352.98859235,  486648.37346181,  241046.47936819,
        350603.81980875,  334362.71879293,  155791.93063477,
        361948.92032935,  443053.59694788,  291650.08198246,
        327294.96189888,  211353.907179  ,  158328.09660029,
        507244.25378788,  343487.63402452,  170047.99595375,
        512132.60467421,  474928.35243468,  472598.77378759,
        489282.81903911,   47987.09387183,  677331.73167261,
        327176.22579329,  204411.40144499,  509726.46752671,
        227873.04865283,   45736.32800452,  385908.42773344,
        427274.19026269,  300009.85270422,  260267.4367132 ,
        152823.59638131,  463446.14607455,  586487.90368669,
        362211.65315336,   40569.73724067,   94423.0154183 ,
        265519.27399314,   14871.17580331,  334613.06136405,
        232863.41131621,  474182.91981474,  195366.70354342,
         12534.42057492,  414709.69505224,  482655.29749553,
        300278.64868976,  333665.70179387,  136849.98432655,
        346601.31777216,  142590.56198429,   93859.08572322,
        254140.30019816,  151045.8301796 ,  281012.6151977 ,
        377760.16058663,  493451.37661999,  275935.76450051,
        471422.75339661,  361185.42182755,  464996.81660996,
        234875.49694879,  976283.45711714,  988546.0963341 ,
        492610.54442306,  486648.37346181,  254406.4998201 ,
        656430.71107945,   96144.70179861,  486595.38735054,
        323745.340196  ,  591080.85724841,  315484.46165711,
        378991.2733722 ,  601951.65448771,  327294.96189888,
        311886.45034513,  328327.51603065,  217283.51848663,
        432778.35236233,   66818.99262609,  197592.42187458,
        136431.97430272,  332103.68244099,  290207.42571158,
       1101090.58334243,  342223.79653817,  478584.24388478,
        383843.11693804,  731614.93429665,  727181.32943419,
        440652.09146865,  500277.41959763,  260058.96906859,
        485104.24535628,  331059.12620788,   44336.78199939,
        268274.08771641,  175138.16564866,  433609.92406441,
        345500.71930198,  360813.69758471,  443053.59694788,
        262287.3073765 ,  293035.43731539,  306463.63923661,
       1443306.40193114,  384711.68563401,  473514.56746644,
        140903.84651215,  520516.09263611,   53684.07610595,
        339154.64336677, 2146150.88231746,  315484.46165711,
        318663.09294695,  509110.07996795,   98302.26212177,
        103534.77492249,  347956.37728064,  595288.46762005,
        726442.60535868,  395786.83374783,  399510.8311307 ,
        -86654.40422121,  334262.42234552,   -9190.43583713,
        406950.99928116,  212028.64381088,  557393.90804432,
        334262.42234552,  -69524.90863607,  617762.36274543,
        247572.19152284,  -90390.46169475,  591886.78718588,
        554160.0188905 ,  561868.83546544,  281882.84086309,
        431409.78584414,  614540.56274264,  387726.78102121,
        239963.68752439,  654069.73525406,  200012.11049215,
        -97953.50484475])

In [38]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5511870728739308

In [39]:
Scores = []
for i in range(1000):
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    Scores.append(r2_score(y_test,y_pred))

In [40]:
np.argmax(Scores)

np.int64(433)

In [41]:
Scores[np.argmax(Scores)]

0.8457046438151008

In [43]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=np.argmax(Scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8457046438151008

In [115]:
import pickle

In [116]:
pickle.dump(pipe,open("LinearRegressionModel.pkl","wb"))

In [117]:
pipe.predict(pd.DataFrame([["Maruti Suzuki Swift","Maruti",2019,100,"Petrol"]],columns=["name","company","year","kms_driven","fuel_type"]))

array([458899.18891749])